<a href="https://colab.research.google.com/github/TAEJIN-KANG/001/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%84%A4%EA%B3%84%EB%B0%8F%ED%99%9C%EC%9A%A9_5%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C_20248191_%EA%B0%95%ED%83%9C%EC%A7%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random  # 파이썬 내장 random 모듈을 가져옵니다.
import numpy as np  # NumPy 라이브러리를 가져옵니다.

# 로또 결과를 저장할 빈 리스트를 만듭니다.
lotto_results = []

# 번호 추출을 3번 반복합니다.
for _ in range(3):
    # 1부터 45까지의 숫자를 포함하는 리스트를 만듭니다.
    a = list(range(1, 46))

    # 리스트를 무작위로 섞습니다.
    random.shuffle(a)

    # 섞인 리스트에서 처음 6개의 숫자를 선택합니다.
    lotto = a[:6]

    # 선택된 로또 번호를 결과 리스트에 추가합니다.
    lotto_results.append(lotto)

# 결과 리스트를 NumPy 배열로 변환하여 (3, 6) 형태로 만듭니다.
lotto_array = np.array(lotto_results)

# 로또 결과를 출력합니다.
print('Lotto Results:\n', lotto_array)

Lotto Results:
 [[40 15 13 31 26  2]
 [11  4 26 19 16 35]
 [12 28 44 25 27  2]]


In [2]:
import numpy as np
# 3차원 배열의 크기를 지정합니다.
shape = (3, 3, 6)
# 3차원 배열을 생성합니다.
arr = np.random.randint(0, 20, shape)
# 3차원 배열을 출력합니다.
print(arr)

[[[ 6 18  3  3  9  9]
  [ 9  2  9  8 10  5]
  [ 4 19  2 15 10 16]]

 [[10 12  7  7 19  1]
  [10  8  4 10 14  6]
  [11  8 11 16  2  5]]

 [[11  9 15  5  0 13]
  [ 1 18 18  0 12  5]
  [ 1  2  6  6 16  9]]]


In [3]:
import numpy as np
# 2차원 배열의 크기를 지정합니다.
shape = (5, 6)
# 2차원 배열을 생성합니다.
arr = np.random.randint(0, 100, shape)
# 2차원 배열을 출력합니다.
print(arr)

[[ 6  7 38 50 52  6]
 [61 52 39 81 45 46]
 [25  1 94 20 68  5]
 [19 89 71 54 37 61]
 [13 23 53 31 61 33]]


In [4]:
import numpy as np

# 0부터 47까지의 값을 생성
temp = np.arange(48)

# 랜덤하게 섞기
np.random.shuffle(temp)

# 3차원 배열로 변환 (4, 3, 4)
array_3d = temp.reshape((4, 3, 4))

# 결과 출력
print("3차원 배열:\n", array_3d)

3차원 배열:
 [[[34  4 29  8]
  [21 14 13 45]
  [16  2 47 20]]

 [[15 11  3 46]
  [35 42 28 12]
  [10  6 27 36]]

 [[30 26 43 39]
  [22 33 31 41]
  [ 9 17 18 25]]

 [[40 44  1 32]
  [ 5 23 19 37]
  [24  7 38  0]]]


In [5]:
import numpy as np

# 0부터 47까지의 값을 생성
temp = np.arange(48)

# 랜덤하게 섞기
np.random.shuffle(temp)

# 2차원 배열로 변환 (6, 8)
array_2d = temp.reshape((6, 8))

# 결과 출력
print("2차원 배열:\n", array_2d)

2차원 배열:
 [[ 1 45 39  0 31 32 34  2]
 [ 4 40 25  3 35 46  6 23]
 [30 42  8 28 13 41 16 36]
 [ 7 38 47 10 29 43 21 22]
 [17 11  9 44 20  5 37 24]
 [27 26 14 15 19 18 12 33]]
